name: travelmate
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  sign_in_button: ^3.0.0
  provider: ^5.0.0
  intl: ^0.17.0
  swipe_cards: ^2.0.0+1
  flutter_card_swiper: ^7.0.0
  story_view: ^0.16.5
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo.svg
    - lib/assets/pasport.svg
    - lib/assets/wallet.svg
